version: '3.9'

services:
  leap-db:
    image: mongo:latest
    container_name: mongodb
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongodb:/data/db
    networks:
      - db
  leap-api:
    container_name: leap-api
    ports:
      - ${FLASK_PORT}:${FLASK_PORT}
    build:
      context: ../ 
      dockerfile: docker/api/Dockerfile
    # environment:
    #   MONGO_USER: root
    #   MONGO_PASS: rootpassword
    #   MONGO_PORT: 27017
    #   MONGO_HOST: mongodb
    depends_on:
      - leap-db
    networks:
      - db

volumes:
  mongodb:

networks:
  db:
    driver: bridge