from flask_restful import Resource
from flask import g, current_app


class Users(Resource):
    def get(self, id: int): ...

    def put(self, id: int): ...

    def post(self): ...
    def delete(self, id: int): ...
